language: java
sudo: true
services:
    - mysql
dist: trusty
jdk: oraclejdk11
before_install:
  - chmod +x mvnw
  - sudo mysql -e 'CREATE DATABASE my_english;'
  - sudo mysql -e "use my_english; update user set authentication_string=PASSWORD('kienkun1990') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql --version
